export const events = [
  {
    id: "1",
    title: "Tech Summit 2025",
    shortDesc: "A 2-day developer conference covering AI, Web3, and cloud technologies.",
    fullDesc:
      "Tech Summit 2025 is the premier developer conference of the year, bringing together 5,000+ engineers, designers, and tech leaders from around the globe. Over two packed days, attendees will explore cutting-edge topics including artificial intelligence, Web3 development, cloud-native architectures, and open-source innovation. Expect keynotes, hands-on workshops, and unmatched networking opportunities.",
    category: "Technology",
    price: 49,
    date: "2025-09-10",
    location: "Dhaka, Bangladesh",
    seats: 500,
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop",
    specs: {
      duration: "2 days",
      format: "In-person",
      level: "All levels",
    },
  },
  {
    id: "2",
    title: "Creative Arts Festival",
    shortDesc: "A celebration of painting, sculpture, and digital art from local artists.",
    fullDesc:
      "The Creative Arts Festival is a vibrant showcase of artistic talent from across Bangladesh. Featuring over 200 artists across painting, sculpture, photography, and digital art, this festival is a feast for the senses. Interactive installations, live demonstrations, and art workshops make this a must-attend event for creatives and art lovers alike.",
    category: "Arts & Culture",
    price: 15,
    date: "2025-10-05",
    location: "Chittagong, Bangladesh",
    seats: 1000,
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&auto=format&fit=crop",
    specs: {
      duration: "3 days",
      format: "In-person",
      level: "All ages",
    },
  },
  {
    id: "3",
    title: "Startup Pitch Night",
    shortDesc: "Early-stage startups pitch to top investors for seed funding.",
    fullDesc:
      "Startup Pitch Night brings together the most promising early-stage startups and seasoned investors under one roof. Selected teams get 5 minutes to pitch their idea, followed by a Q&A with a panel of venture capitalists and angel investors. Whether you're a founder looking for funding or an investor scouting the next big thing, this event is the place to be.",
    category: "Business",
    price: 0,
    date: "2025-08-22",
    location: "Dhaka, Bangladesh",
    seats: 200,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800&auto=format&fit=crop",
    specs: {
      duration: "1 evening",
      format: "In-person",
      level: "Entrepreneurs & Investors",
    },
  },
  {
    id: "4",
    title: "Music & Beats Concert",
    shortDesc: "Live performances by top local and international music artists.",
    fullDesc:
      "Music & Beats Concert is an electrifying night of live music featuring some of the most exciting artists on the scene today. From indie rock to electronic beats, the lineup spans multiple genres to keep the energy high all night. Food stalls, merchandise booths, and an amazing atmosphere make this more than just a concert — it's an experience.",
    category: "Music",
    price: 25,
    date: "2025-11-15",
    location: "Sylhet, Bangladesh",
    seats: 3000,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&auto=format&fit=crop",
    specs: {
      duration: "1 night",
      format: "In-person",
      level: "All ages",
    },
  },
  {
    id: "5",
    title: "Health & Wellness Expo",
    shortDesc: "Explore the latest in fitness, nutrition, and mental wellness.",
    fullDesc:
      "The Health & Wellness Expo is a comprehensive event dedicated to helping you live your best life. With over 100 exhibitors covering fitness equipment, organic nutrition, mental health services, yoga studios, and holistic therapies, there's something for everyone. Attend free seminars from leading health professionals and walk away with practical tools to improve your wellbeing.",
    category: "Health",
    price: 10,
    date: "2025-09-28",
    location: "Rajshahi, Bangladesh",
    seats: 800,
    rating: 4.3,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&auto=format&fit=crop",
    specs: {
      duration: "2 days",
      format: "In-person",
      level: "All ages",
    },
  },
  {
    id: "6",
    title: "Food & Culture Carnival",
    shortDesc: "A culinary journey through Bangladesh's diverse regional cuisines.",
    fullDesc:
      "The Food & Culture Carnival is a celebration of Bangladesh's rich culinary heritage. Sample dishes from all 8 divisions, watch live cooking demonstrations by celebrity chefs, and participate in cooking competitions. Cultural performances, folk music, and handicraft stalls round out this immersive experience that brings communities together through the universal language of food.",
    category: "Food",
    price: 5,
    date: "2025-12-01",
    location: "Khulna, Bangladesh",
    seats: 2000,
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop",
    specs: {
      duration: "2 days",
      format: "In-person",
      level: "All ages",
    },
  },
  {
    id: "7",
    title: "Photography Masterclass",
    shortDesc: "Learn professional photography techniques from award-winning photographers.",
    fullDesc:
      "This intensive Photography Masterclass is designed for enthusiasts who want to take their skills to the next level. Led by three award-winning photographers, the class covers composition, lighting, post-processing in Lightroom, and building a professional portfolio. Limited to 30 participants for a personalized learning experience. Camera equipment provided for those who need it.",
    category: "Education",
    price: 75,
    date: "2025-10-18",
    location: "Dhaka, Bangladesh",
    seats: 30,
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800&auto=format&fit=crop",
    specs: {
      duration: "1 day",
      format: "Workshop",
      level: "Intermediate",
    },
  },
  {
    id: "8",
    title: "Gaming Tournament 2025",
    shortDesc: "Compete in BGMI, FIFA, and Valorant for exciting cash prizes.",
    fullDesc:
      "Gaming Tournament 2025 is the biggest esports event in Bangladesh, featuring competitive brackets across BGMI, FIFA 25, and Valorant. Solo and team registrations are open to all skill levels. Top prizes include cash rewards, gaming peripherals, and sponsorship opportunities with leading gaming brands. Spectators are welcome — come cheer your favorite players live.",
    category: "Gaming",
    price: 20,
    date: "2025-11-30",
    location: "Chittagong, Bangladesh",
    seats: 400,
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop",
    specs: {
      duration: "2 days",
      format: "In-person",
      level: "All levels",
    },
  },
];